var searchData=
[
  ['s_5fi5g_17143',['s_i5g',['../structs__i5g.html',1,'']]],
  ['s_5fi5g_5finit_17144',['s_i5g_init',['../structs__i5g__init.html',1,'']]],
  ['sd_5fdesc_17145',['sd_desc',['../structsd__desc.html',1,'']]],
  ['sd_5finit_5fparam_17146',['sd_init_param',['../structsd__init__param.html',1,'']]],
  ['spi_5fdesc_17147',['spi_desc',['../structspi__desc.html',1,'']]],
  ['spi_5fdevice_17148',['spi_device',['../structspi__device.html',1,'']]],
  ['spi_5fengine_5fcmd_5fqueue_17149',['spi_engine_cmd_queue',['../structspi__engine__cmd__queue.html',1,'']]],
  ['spi_5fengine_5fdesc_17150',['spi_engine_desc',['../structspi__engine__desc.html',1,'']]],
  ['spi_5fengine_5finit_5fparam_17151',['spi_engine_init_param',['../structspi__engine__init__param.html',1,'']]],
  ['spi_5fengine_5fmsg_17152',['spi_engine_msg',['../structspi__engine__msg.html',1,'']]],
  ['spi_5fengine_5foffload_5finit_5fparam_17153',['spi_engine_offload_init_param',['../structspi__engine__offload__init__param.html',1,'']]],
  ['spi_5fengine_5foffload_5fmessage_17154',['spi_engine_offload_message',['../structspi__engine__offload__message.html',1,'']]],
  ['spi_5finit_5fparam_17155',['spi_init_param',['../structspi__init__param.html',1,'']]],
  ['spi_5fplatform_5fops_17156',['spi_platform_ops',['../structspi__platform__ops.html',1,'']]],
  ['spisettings_5ft_17157',['spiSettings_t',['../structspi_settings__t.html',1,'']]],
  ['std_5ftiming_17158',['std_timing',['../structstd__timing.html',1,'']]],
  ['strg_5fdesc_17159',['strg_desc',['../structstrg__desc.html',1,'']]],
  ['synthlut_17160',['SynthLUT',['../struct_synth_l_u_t.html',1,'']]]
];
